services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./app:/var/www/html/app
      - ./config/dev/virtualhosts/frontend.api.dev.conf:/etc/apache2/sites-enabled/frontend.api.dev.conf
      - ./config/dev/virtualhosts/urls.js:/var/www/html/app/public_html/config/urls.js
    ports:
      - "8081:80"

